const ROUTES = {
    LOGIN: '/',
    REGISTRATION: '/registration',
    FORGOT_PASSWORD: '/forgot-password',
    PROFILE: '/profile',
    PROFILE_EDITING: '/profile-editing',
    AVAILABLE_TESTS: '/available-tests',
    AVAILABLE_TEST: '/available-test',
    UPLOAD_DOCUMENTS: '/upload-documents',
    DOCUMENTS_EDITING: '/documents-editing',
    MY_QUALIFICATIONS: '/my-qualifications',
    QUALIFICATION_EDITING: '/qualification-editing',
    QUALIFICATION_DETAIL: '/qualification-detail',
    CERTIFICATION_RESULTS: '/certification-results',
    TEST_DETAIL: '/test-detail',
    QUALIFICATION_ADDED: '/qualification-added',
    THEORETICAL_PART: '/theoretical-part',
    CERTIFICATION_RESULTS_DETAIL: '/certification-results_detail',
    APPILYNG: '/appilyng',
    USERS_ATTESTED: '/users-attested',
    PRACTICAL_PART: '/practical-part',
    USERS: '/users',
    USERS_DETAIL: '/users',
    ATTESTATION_QUALI: '/attestation_qualification',
    ATTESTATION_PROTOCOL: '/attestation_protocol',
    ATTESTATION_TESTS_BANK: '/attestation_tests_bank',
    ATTESTATION_QUESTIONS_BANK: '/attestation_questions_bank',
    EXAMINATION_GROUPS: '/examination-groups',
    USER_APPLICATIONS: '/user-applocations',
    CERTIFIED: '/certified',
    EXAM_SCHEDULE: '/exam-schedule',
    TEST_PROCESSING: '/test-processing',
    USER_APPLICATIONS_DETAIL: '/user-applications-detail',
    LPR_USERS: '/lpr-users',
    LPR_USERS_DETAIL: '/lpr-users',
    CERTIFIED_DETAIL: '/certified-detail',
    TEST_RESULT: '/test-result',
    // THEORETICAL_PART_EXPERT: '/theoretical-part-expert',
    // PRACTICAL_PART_EXPERT: '/practical-part-expert',
    LPR_EXAM: '/lpr-exam',
    ADMIN_USERS: '/admin-users',
    ADMIN_EXAM: '/admin-exam',
    EXPERT: '/expert',
    MODERATOR: '/moderator',
    MODERATOR_TEST_RESULT: '/moderator-test-result',
    ATTESTED_APPEAL: '/attested-appeal',
    SURVEYS_PART: '/surveys-part',
}

export default ROUTES
