const ROUTES = {
    LOGIN: '/',
    REGISTRATION: '/registration',
    FORGOT_PASSWORD: '/forgot-password',
    PROFILE: '/profile',
    PROFILE_EDITING: '/profile-editing',
    AVAILABLE_TESTS: '/available-tests',
    AVAILABLE_TEST: '/available-test',
    TEST_RESULTS: '/test-results',
    TEST_RESULT: '/test-result',
    DOCUMENTS: '/documents',
    DOCUMENTS_EDITING: '/documents-editing',
    MY_QUALIFICATIONS: '/my-qualifications',
    QUALIFICATION_EDITING: '/qualification-editing',
    QUALIFICATION_DETAIL: '/qualification-detail',
    CERTIFICATION_RESULTS: '/certification-results',
    TEST_DETAIL: '/test-detail',
    QUALIFICATION_ADDED: '/qualification-added',
    THEORETICAL_PART: '/theoretical-part',
    CERTIFICATION_RESULTS_DETAIL: '/certification-results_detail',
    APPILYNG: '/appilyng',
    USERS_ATTESTED: '/users-attested',
    PRACTICAL_PART: '/practical-part',
    USERS: '/users',
    USERS_DETAIL: '/users',
    ATTESTATION_QUALI: '/attestation_qualification',
    ATTESTATION_TESTS_BANK: '/attestation_tests_bank',
    ATTESTATION_QUESTIONS_BANK: '/attestation_questions_bank',
}

export default ROUTES
